# Generated by Django 5.1.2 on 2024-11-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_plan_alter_client_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_clients',
            field=models.IntegerField(default=5, verbose_name='Maximum Clients'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_leads',
            field=models.IntegerField(default=5, verbose_name='Maximum Leads'),
        ),
    ]
